audit_header: false
title: Team 1 Realty Real Estate Video Blog
description: >-
  If you are looking to buy or sell a home, get all the information and the
  latest updates, tips, and tricks from Team1Realty - your professional East Bay
  Area Real Estate Agents.
show_custom_links: false
custom_links:
  - title:
    url:
client:
  name: Ty Leon-Guerrero
  license: 'BRE#: 01177486'
  about_markdown: >-
    I am the Broker/Owner of Team 1 Realty. I've been selling & brokering
    properties since 1994 and investing since 1993, all right here, in the local
    area. As a Real Estate Broker, I’ve PERSONALLY sold & closed well over 2000+
    Properties.


    As an Investor, I have personally bought and sold (as a principal) 200+
    properties as rentals, “Fix and Flip”, repositioning, and development
    projects. My team and I have always been actively involved in all phases of
    Foreclosure Real Estate since 1994.
  market: East Bay Area
  brand: Team1Realty
  brokerage:
  address:
  phone: 800-533-7107
  email: TY@TYLG.COM
  url: www.team1realty.com
  url2: wealsobuyhouses.com
  first_CTA_text: Home Evaluation
  first_CTA_URL: 'http://www.team1realty.com/cma/property-valuation/'
  second_CTA_text: Home Search
  second_CTA_URL: 'http://www.team1realty.com/search/advanced_search/'
  phone_CTA: true
  VR_form: 'http://oi.vresp.com?fid=9676bb12bc'
welcome_headline: Get Educated About Real Estate
welcome_text_markdown: >-
  Our mission at Team 1 Realty is to be your best resource for real estate
  advice. Whether you are a buyer, seller, or investor, our team of
  professionals can answer any questions you might have about real estate.
  Subscribe to this blog to get the latest news on local market trends and
  receive expert tips for buying or selling a home.
socials:
  review_sm_icons: false
  facebook_url: 'https://www.facebook.com/team1realty/'
  linkedin_url: 'https://www.linkedin.com/in/tyleonguerrero/'
  gplus_url: 'https://plus.google.com/u/0/102891058249334984597'
  youtube_url: 'https://www.youtube.com/user/tylg123'
  twitter_url: 'https://twitter.com/tylg'
  instagram_url:
  pinterest_url:
  zillow_url: 'http://www.zillow.com/profile/Ty-LG/'
  trulia_url: >-
    https://www.trulia.com/profile/ty-leon-guerrero-agent-walnut-creek-ca-zg6rm4hn/overview
  yelp_url:
  podcast_url: >-
    https://itunes.apple.com/us/podcast/team1realty-real-estate-podcast/id1175098882?mt=2
podcast:
  title: Team1Realty Real Estate Podcast
  categories:
  image: /img/Leon_podcast.png
  subtitle: >-
    Learn all the tips, tricks and more for buyers and sellers in the East Bay
    Area Area Real Estate Market
  description: >-
    If you are looking to buy or sell a home, get all the information and the
    latest updates, tips, and tricks from Team1Realty - your professional East
    Bay Area Real Estate Agents.
  keywords: >-
    Real Estate for sale, Real Estate agents, top real estate agents, local real
    estate agents, find a real estate agent, houses for sale in San Francisco,
    home selling tips, home for sale, home buying, home buying process, property
    finder, property search, property, real estate market, estate agent,
    realestate, real estate listings, buying a house, homes for sale, mls, home
    buyer
  author:
images:
  client_headshot_path: /img/headshot.png
  hero_logo_path: /img/logo.png
  hero_text: Real Estate Video Blog
  hero_background_hex: '#1965b0'
  hero_image_path: /img/background.jpg
brand_color: '#1965b0'
theme_color: '#111111'
theme_text_color: '#ffffff'
main_body_color: '#ffffff'
main_body_text_color: '#353535'